apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: category-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rahadiangg/service-deployment.git
    targetRevision: HEAD
    path: category-api/k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
