apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-crud
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rahadiangg/service-deployment.git
    targetRevision: HEAD
    path: express-crud/k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
