apiVersion: v1
kind: Secret
metadata:
  name: category-api-secret
type: Opaque
data:
  DB_HOST: MTcyLjI5LjAuMTk2
  DB_USER: Y2NlLWRlbW8=
  DB_PASS: Y2NlMjAyMiEh
  DB_NAME: Y2F0ZWdvcnktYXBp
  APP_PORT: ODA4MA==
